### PR TITLE
Fix/bug with insert update ftmutableset fixes

### PR DESCRIPTION
**Pull request by pawelropa**
This Pull request fixes issue #2

### CODE REVIEW

**Comment by anagromataf** [comment]
Unfortunately the the `-[FTMutableSetTests testUpdateDoesNotContainSameIndexes]` failed on iOS and on OS X.

```
FTMutableSetTests.m:296: error: -[FTMutableSetTests testUpdateDoesNotContainSameIndexes] : Expected 1 matching invocation, but received 0
```

**Comment by pawelropa** [comment]
@anagromataf Updated the OCMockito and OCHamrest - this was needed for the use of `HCArgumentCaptor`. Tests should pass now (they sometimes do not, seems to be some kind of `Xcode` issue), if they don't (for OSX) just do a `Clean` and `Clean build folder...` and run the tests again, this works for me...

**Comment by anagromataf** [comment]
@pawelropa Thanks for the contribution so for.

It seams, that the test is failing because of something random. It I run the tests many times they are passing some times and failing some times (somehow 1:1). Unfortunately I don't have time at the moment to look deeper into this.

**Comment by pawelropa** [comment]
@anagromataf Sure, no problem - I will also try to investigate why it fails randomly.

**Comment by anagromataf** [comment]
@pawelropa Fix is in version 2.2.1-beta.2

**Pull request closed without merging**
